Added notification to all components when changes will be lost
CohesionForce/kohese-server pull request #55
Opened 2022-01-06 22:36 UTC by dadamek

Task: Provide warning to user when changes will be lost (8443b430-6d7a-11ec-8419-fbd10f9c9d1c)

2022-01-18 16:31 UTC, tpitts-CFI commented
> * In Admin component, Journal Component => If I select to discard the changes, the Dirty Indicator remains until I navigate away from the selected item
> * Modifying an item on the Project Status -> Board (in dashboard) does not provided a warning before discard.

This is not an issue with this task. It is being fixed with two other tasks:
* Task: Handle creates, deletes and updates in session service (66617cd0-6f29-11ec-8419-fbd10f9c9d1c)
* Task: User and Session Push Notification (aa7df250-e001-11e8-a3f0-ed214af03fd6)

2022-01-18 17:06 UTC, tpitts-CFI requested changes
Tpitts review

2022-01-18 17:06 UTC, tpitts-CFI commented on kohese-portal/client/src/components/document-view/document-row/document-row.component.ts
> +      await this._itemRepository.fetchItem(this.docInfo.proxy);
line 199 may be removed

2022-01-18 17:06 UTC, tpitts-CFI commented on kohese-portal/client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.ts
> +import { proxy } from 'jquery';
remove this import

2022-01-18 17:19 UTC, dadamek commented on kohese-portal/client/src/components/dashboard/project-dashboard/status-dashboard/state-bar-chart/state-summary-dialog/state-summary-dialog.component.ts
> +        await this._itemRepository.fetchItem(TreeConfiguration.getWorkingTree().getProxyFor(itemProxy.item.id));
fixed

2022-01-18 17:19 UTC, dadamek commented on kohese-portal/client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.ts
> +        await this._itemRepository.fetchItem(TreeConfiguration.getWorkingTree().getProxyFor(itemProxy.item.id));
fixed

2022-01-18 17:19 UTC, dadamek commented on kohese-portal/client/src/components/details/journal/journal.component.ts
> +        this._itemRepository.fetchItem(TreeConfiguration.getWorkingTree().getProxyFor(itemProxy.item.id));
fixed

2022-01-18 17:19 UTC, dadamek commented on kohese-portal/client/src/components/details/journal/journal.component.ts
> +
fixed

2022-01-18 17:20 UTC, dadamek commented on kohese-portal/client/src/components/document-view/document-row/document-row.component.ts
> +      await this._itemRepository.fetchItem(this.docInfo.proxy);
fixed

2022-01-18 17:27 UTC, dadamek commented on kohese-portal/client/src/components/dashboard/assignment-dashboard/assignment-dashboard.component.ts
> +import { proxy } from 'jquery';
fixed

2022-01-18 17:43 UTC, tpitts-CFI approved these changes
all comments were addressed. I am okay with this merge request.

2022-01-28 17:51 UTC, gmckune requested changes
1.  Project Status board is working.  Changes were discarded and Dirty flag went away.
2. Journal Component still not working.  Dirty flag doesn't go away until mouse is moved and changes remain that I wanted discarded.  But, the changes that I wanted discarded disappear if I click edit again.
3. Admin changes were not retested.  However, need to determine which task will fix the problem here (since two tasks are identified).

2022-01-28 19:34 UTC, gmckune approved these changes

2022-01-28 19:37 UTC, merged